local M = {}

function M.apply(r)
    local hl = function(name, opts)
        vim.api.nvim_set_hl(0, name, opts)
    end

    -- -------------------------------------------------------------------------
    -- Editor UI
    -- -------------------------------------------------------------------------
    hl("Normal",           { fg = r.fg,              bg = r.bg })
    hl("NormalFloat",      { fg = r.fg,              bg = r.bg_dark })
    hl("NormalNC",         { fg = r.fg_dim,          bg = r.bg })
    hl("ColorColumn",      { bg = r.bg_light })
    hl("CursorColumn",     { bg = r.cursor_line })
    hl("CursorLine",       { bg = r.cursor_line })
    hl("CursorLineNr",     { fg = r.cursor_line_nr,  bold = true })
    hl("LineNr",           { fg = r.line_nr,          bold = true })
    hl("SignColumn",       { fg = r.line_nr,         bg = r.bg })
    hl("FoldColumn",       { fg = r.fold,            bg = r.bg })
    hl("Folded",           { fg = r.fold,            bg = r.bg_light })
    hl("VertSplit",        { fg = r.border,          bg = r.bg })
    hl("WinSeparator",     { fg = r.border,          bg = r.bg })
    hl("EndOfBuffer",      { fg = r.non_text })
    hl("NonText",          { fg = r.non_text })
    hl("Whitespace",       { fg = r.non_text })
    hl("SpecialKey",       { fg = r.special_key })
    hl("MatchParen",       { fg = r.match_paren,     bold = true,  underline = true })
    hl("Conceal",          { fg = r.non_text })

    -- Search & selection
    hl("Visual",           { bg = r.visual })
    hl("VisualNOS",        { bg = r.visual })
    hl("Search",           { fg = r.search_fg,       bg = r.search_bg })
    hl("IncSearch",        { fg = r.incsearch_fg,    bg = r.incsearch_bg, bold = true })
    hl("Substitute",       { fg = r.incsearch_fg,    bg = r.incsearch_bg })
    hl("QuickFixLine",     { bg = r.bg_light })

    -- Statusline / tabline
    hl("StatusLine",       { fg = r.statusline_fg,   bg = r.statusline_bg })
    hl("StatusLineNC",     { fg = r.statusline_nc,   bg = r.statusline_bg })
    hl("TabLine",          { fg = r.statusline_nc,   bg = r.tabline_bg })
    hl("TabLineFill",      { bg = r.tabline_bg })
    hl("TabLineSel",       { fg = r.tabline_sel,     bg = r.bg,     bold = true })
    hl("WinBar",           { fg = r.fg_dim,          bg = r.bg })
    hl("WinBarNC",         { fg = r.statusline_nc,   bg = r.bg })

    -- Popup menu
    hl("Pmenu",            { fg = r.fg,              bg = r.pmenu_bg })
    hl("PmenuSel",         { fg = r.pmenu_sel_fg,    bg = r.pmenu_sel_bg })
    hl("PmenuSbar",        { bg = r.bg_light })
    hl("PmenuThumb",       { bg = r.pmenu_thumb })

    -- Floating windows / borders
    hl("FloatBorder",      { fg = r.border,          bg = r.bg_dark })
    hl("FloatTitle",       { fg = r.title,           bg = r.bg_dark,  bold = true })

    -- Messages & prompts
    hl("ErrorMsg",         { fg = r.error_msg,       bold = true })
    hl("WarningMsg",       { fg = r.warning_msg })
    hl("MoreMsg",          { fg = r.diag_info })
    hl("Question",         { fg = r.diag_info })
    hl("ModeMsg",          { fg = r.fg_bright,       bold = true })
    hl("MsgArea",          { fg = r.fg })
    hl("MsgSeparator",     { fg = r.border })

    -- Misc
    hl("Title",            { fg = r.title,           bold = true })
    hl("Directory",        { fg = r.directory })
    hl("WildMenu",         { fg = r.pmenu_sel_fg,    bg = r.pmenu_sel_bg })

    -- Diff
    hl("DiffAdd",          { fg = r.diff_add,        bg = r.bg_light })
    hl("DiffChange",       { fg = r.diff_change,     bg = r.bg_light })
    hl("DiffDelete",       { fg = r.diff_delete,     bg = r.bg_light })
    hl("DiffText",         { fg = r.diff_text,       bg = r.bg_light, bold = true })

    -- Spell
    hl("SpellBad",         { sp = r.diag_error,      undercurl = true })
    hl("SpellCap",         { sp = r.diag_warn,       undercurl = true })
    hl("SpellLocal",       { sp = r.diag_info,       undercurl = true })
    hl("SpellRare",        { sp = r.diag_hint,       undercurl = true })

    -- -------------------------------------------------------------------------
    -- Classic syntax groups
    -- -------------------------------------------------------------------------
    hl("Comment",          { fg = r.comment,         italic = true })
    hl("Constant",         { fg = r.constant })
    hl("String",           { fg = r.string })
    hl("Character",        { fg = r.character })
    hl("Number",           { fg = r.number })
    hl("Boolean",          { fg = r.boolean })
    hl("Float",            { fg = r.number })
    hl("Identifier",       { fg = r.variable })
    hl("Function",         { fg = r["function"],     bold = true })
    hl("Statement",        { fg = r.keyword })
    hl("Conditional",      { fg = r.keyword })
    hl("Repeat",           { fg = r.keyword })
    hl("Label",            { fg = r.label })
    hl("Operator",         { fg = r.operator })
    hl("Keyword",          { fg = r.keyword })
    hl("Exception",        { fg = r.keyword_return })
    hl("PreProc",          { fg = r.preproc })
    hl("Include",          { fg = r.include })
    hl("Define",           { fg = r.macro })
    hl("Macro",            { fg = r.macro })
    hl("PreCondit",        { fg = r.preproc })
    hl("Type",             { fg = r.type })
    hl("StorageClass",     { fg = r.storage })
    hl("Structure",        { fg = r.structure })
    hl("Typedef",          { fg = r.type })
    hl("Special",          { fg = r.special })
    hl("SpecialChar",      { fg = r.string_escape })
    hl("Tag",              { fg = r.tag })
    hl("Delimiter",        { fg = r.delimiter })
    hl("SpecialComment",   { fg = r.doc_comment,     italic = true })
    hl("Debug",            { fg = r.diag_warn })
    hl("Underlined",       { underline = true })
    hl("Error",            { fg = r.error_token,     bold = true })
    hl("Todo",             { fg = r.todo,            bg = r.todo_bg })

    -- -------------------------------------------------------------------------
    -- Treesitter
    -- -------------------------------------------------------------------------
    hl("@variable",                    { fg = r.variable })
    hl("@variable.builtin",            { fg = r.variable_builtin })
    hl("@variable.parameter",          { fg = r.parameter })
    hl("@variable.member",             { fg = r.field })
    hl("@constant",                    { fg = r.constant })
    hl("@constant.builtin",            { fg = r.boolean })
    hl("@constant.macro",              { fg = r.macro })
    hl("@module",                      { fg = r.namespace })
    hl("@module.builtin",              { fg = r.variable_builtin })
    hl("@label",                       { fg = r.label })
    hl("@string",                      { fg = r.string })
    hl("@string.documentation",        { fg = r.doc_comment,   italic = true })
    hl("@string.regexp",               { fg = r.string_escape })
    hl("@string.escape",               { fg = r.string_escape })
    hl("@string.special",              { fg = r.special })
    hl("@character",                   { fg = r.character })
    hl("@character.special",           { fg = r.string_escape })
    hl("@boolean",                     { fg = r.boolean })
    hl("@number",                      { fg = r.number })
    hl("@number.float",                { fg = r.number })
    hl("@type",                        { fg = r.type })
    hl("@type.builtin",                { fg = r.type_builtin })
    hl("@type.definition",             { fg = r.type })
    hl("@attribute",                   { fg = r.preproc })
    hl("@property",                    { fg = r.field })
    hl("@function",                    { fg = r["function"],   bold = true })
    hl("@function.builtin",            { fg = r.func_builtin,  bold = true })
    hl("@function.call",               { fg = r["function"],   bold = true })
    hl("@function.macro",              { fg = r.macro })
    hl("@function.method",             { fg = r.method,        bold = true })
    hl("@function.method.call",        { fg = r.method,        bold = true })
    hl("@constructor",                 { fg = r.type })
    hl("@operator",                    { fg = r.operator })
    hl("@keyword",                     { fg = r.keyword })
    hl("@keyword.coroutine",           { fg = r.keyword })
    hl("@keyword.function",            { fg = r.keyword })
    hl("@keyword.operator",            { fg = r.operator })
    hl("@keyword.import",              { fg = r.include })
    hl("@keyword.type",                { fg = r.storage })
    hl("@keyword.modifier",            { fg = r.storage })
    hl("@keyword.repeat",              { fg = r.keyword })
    hl("@keyword.return",              { fg = r.keyword_return })
    hl("@keyword.debug",               { fg = r.diag_warn })
    hl("@keyword.exception",           { fg = r.keyword_return })
    hl("@keyword.conditional",         { fg = r.keyword })
    hl("@keyword.conditional.ternary", { fg = r.operator })
    hl("@keyword.directive",           { fg = r.preproc })
    hl("@keyword.directive.define",    { fg = r.macro })
    hl("@punctuation.delimiter",       { fg = r.delimiter })
    hl("@punctuation.bracket",         { fg = r.delimiter })
    hl("@punctuation.special",         { fg = r.special })
    hl("@comment",                     { fg = r.comment,       italic = true })
    hl("@comment.documentation",       { fg = r.doc_comment,   italic = true })
    hl("@comment.error",               { fg = r.diag_error,    bold = true })
    hl("@comment.warning",             { fg = r.diag_warn,     bold = true })
    hl("@comment.todo",                { fg = r.todo,          bold = true })
    hl("@comment.note",                { fg = r.diag_info,     bold = true })

    -- Markup (markdown, rst, etc.)
    hl("@markup.strong",               { bold = true })
    hl("@markup.italic",               { italic = true })
    hl("@markup.strikethrough",        { strikethrough = true })
    hl("@markup.underline",            { underline = true })
    hl("@markup.heading",              { fg = r.title,         bold = true })
    hl("@markup.heading.1",            { fg = r.title,         bold = true })
    hl("@markup.heading.2",            { fg = r["function"],   bold = true })
    hl("@markup.heading.3",            { fg = r.type,          bold = true })
    hl("@markup.quote",                { fg = r.comment,       italic = true })
    hl("@markup.math",                 { fg = r.number })
    hl("@markup.link",                 { fg = r.blue,          underline = true })
    hl("@markup.link.label",           { fg = r.blue })
    hl("@markup.link.url",             { fg = r.string,        underline = true })
    hl("@markup.raw",                  { fg = r.string_escape })
    hl("@markup.raw.block",            { fg = r.string_escape })
    hl("@markup.list",                 { fg = r.special })
    hl("@markup.list.checked",         { fg = r.diff_add })
    hl("@markup.list.unchecked",       { fg = r.non_text })

    -- Diff (treesitter)
    hl("@diff.plus",                   { fg = r.diff_add })
    hl("@diff.minus",                  { fg = r.diff_delete })
    hl("@diff.delta",                  { fg = r.diff_change })

    -- Tags (HTML/XML/JSX)
    hl("@tag",                         { fg = r.tag })
    hl("@tag.builtin",                 { fg = r.tag })
    hl("@tag.attribute",               { fg = r.tag_attr })
    hl("@tag.delimiter",               { fg = r.tag_delim })

    -- -------------------------------------------------------------------------
    -- LSP diagnostics
    -- -------------------------------------------------------------------------
    hl("DiagnosticError",              { fg = r.diag_error })
    hl("DiagnosticWarn",               { fg = r.diag_warn })
    hl("DiagnosticInfo",               { fg = r.diag_info })
    hl("DiagnosticHint",               { fg = r.diag_hint })
    hl("DiagnosticOk",                 { fg = r.diag_ok })

    hl("DiagnosticVirtualTextError",   { fg = r.diag_error,    italic = true })
    hl("DiagnosticVirtualTextWarn",    { fg = r.diag_warn,     italic = true })
    hl("DiagnosticVirtualTextInfo",    { fg = r.diag_info,     italic = true })
    hl("DiagnosticVirtualTextHint",    { fg = r.diag_hint,     italic = true })

    hl("DiagnosticUnderlineError",     { sp = r.diag_error,    undercurl = true })
    hl("DiagnosticUnderlineWarn",      { sp = r.diag_warn,     undercurl = true })
    hl("DiagnosticUnderlineInfo",      { sp = r.diag_info,     undercurl = true })
    hl("DiagnosticUnderlineHint",      { sp = r.diag_hint,     undercurl = true })

    hl("DiagnosticFloatingError",      { fg = r.diag_error })
    hl("DiagnosticFloatingWarn",       { fg = r.diag_warn })
    hl("DiagnosticFloatingInfo",       { fg = r.diag_info })
    hl("DiagnosticFloatingHint",       { fg = r.diag_hint })

    hl("DiagnosticSignError",          { fg = r.diag_error })
    hl("DiagnosticSignWarn",           { fg = r.diag_warn })
    hl("DiagnosticSignInfo",           { fg = r.diag_info })
    hl("DiagnosticSignHint",           { fg = r.diag_hint })

    -- LSP references & inlay hints
    hl("LspReferenceText",             { bg = r.lsp_ref })
    hl("LspReferenceRead",             { bg = r.lsp_ref_read })
    hl("LspReferenceWrite",            { bg = r.lsp_ref_write })
    hl("LspInlayHint",                 { fg = r.inlay_hint,    italic = true })
    hl("LspCodeLens",                  { fg = r.inlay_hint,    italic = true })
    hl("LspCodeLensSeparator",         { fg = r.border })
end

return M
